name: RustDesk smoke test
on:
  workflow_dispatch:
  push:
    paths:
      - "docker-compose.yml"
      - ".github/workflows/rustdesk-ci.yml"

jobs:
  compose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare data dir
        run: mkdir -p data

      - name: Compose up
        run: |
          docker compose version
          docker compose up -d
          sleep 8
          docker ps

      - name: Show logs
        run: |
          docker logs --tail=80 hbbr || true
          docker logs --tail=80 hbbs || true

      - name: Health check
        run: |
          docker exec hbbr sh -c 'pidof hbbr'
          docker exec hbbs sh -c 'pidof hbbs'

      - name: Tear down
        if: always()
        run: docker compose down -v
