# .github/workflows/rustdesk-ci.yml
name: RustDesk smoke test
on: workflow_dispatch

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Start hbbr & hbbs
        run: |
          docker network create rustdesk || true

          docker run -d --name hbbr --network rustdesk \
            -v ${{ github.workspace }}/data:/root \
            -p 21115:21115 -p 21116:21116 -p 21116:21116/udp -p 21118:21118 \
            rustdesk/rustdesk-server:latest hbbr

          docker run -d --name hbbs --network rustdesk \
            -v ${{ github.workspace }}/data:/root \
            -p 21114:21114 -p 21115:21115 -p 21116:21116 -p 21116:21116/udp -p 21118:21118 \
            rustdesk/rustdesk-server:latest hbbs

          sleep 5
          docker ps
          docker logs --tail=50 hbbr || true
          docker logs --tail=50 hbbs || true
